# Generated by Django 3.0.7 on 2020-11-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowd',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
